// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB74kNkPqIr2qqsRCEs1Qcln4OfjWzBuGQ',
    appId: '1:622769924606:web:8af2b1855632556c86b8af',
    messagingSenderId: '622769924606',
    projectId: 'stuff-coll-d4523',
    authDomain: 'stuff-coll-d4523.firebaseapp.com',
    storageBucket: 'stuff-coll-d4523.firebasestorage.app',
    measurementId: 'G-NDVR54J11N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSKz5BXfWuOCrYlEYUCxNwMbCKdyPdSAI',
    appId: '1:622769924606:android:3f675739f57ff0d086b8af',
    messagingSenderId: '622769924606',
    projectId: 'stuff-coll-d4523',
    storageBucket: 'stuff-coll-d4523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0nJ3Iju0qsFcfEveINRDurI6iNY3VCaU',
    appId: '1:622769924606:ios:ae640c32125bd64a86b8af',
    messagingSenderId: '622769924606',
    projectId: 'stuff-coll-d4523',
    storageBucket: 'stuff-coll-d4523.firebasestorage.app',
    iosBundleId: 'com.example.stuffCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB74kNkPqIr2qqsRCEs1Qcln4OfjWzBuGQ',
    appId: '1:622769924606:web:d90d3a494b7707d286b8af',
    messagingSenderId: '622769924606',
    projectId: 'stuff-coll-d4523',
    authDomain: 'stuff-coll-d4523.firebaseapp.com',
    storageBucket: 'stuff-coll-d4523.firebasestorage.app',
    measurementId: 'G-WMTZJ7M6E6',
  );
}
